# Generated by Django 4.2.29 on 2026-04-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('color', models.CharField(default='#4CC9F0', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Asset categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MacroSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('signal_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('regime', models.CharField(max_length=64)),
                ('status_color', models.CharField(default='cyan', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('asset_type', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=80)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='OPERATIVE', max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('panel', models.CharField(choices=[('OVERVIEW', 'Overview'), ('PORTFOLIO', 'Portfolio'), ('MACRO', 'Macro'), ('REAL_ESTATE', 'Real Estate')], default='OVERVIEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ticker', models.CharField(blank=True, max_length=24)),
                ('bucket_name', models.CharField(max_length=100)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HOLD', 'Hold'), ('PENDING', 'Pending'), ('WATCH', 'Watch')], default='ACTIVE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.assetcategory')),
            ],
            options={
                'ordering': ['-current_value', 'name'],
            },
        ),
    ]
